<?php

$list = [
    [
        (!empty($_POST["household_id"]) ? $_POST["household_id"] : '99'),
        (!empty($_POST["person_id"]) ? $_POST["person_id"] : '99'),

        //day 1 trip 1
        (!empty($_POST["day1_trip1_origin"]) ? $_POST["day1_trip1_origin"] : '99'),
        (!empty($_POST["day1_trip1_destination"]) ? $_POST["day1_trip1_destination"] : '99'),
        (!empty($_POST["day1_trip1_purpose"]) ? $_POST["day1_trip1_purpose"] : '99'),
        (!empty($_POST["day1_trip1_segment1_mode"]) ? $_POST["day1_trip1_segment1_mode"] : '99'),
        (!empty($_POST["day1_trip1_segment2_mode"]) ? $_POST["day1_trip1_segment2_mode"] : '99'),
        (!empty($_POST["day1_trip1_segment3_mode"]) ? $_POST["day1_trip1_segment3_mode"] : '99'),
        (!empty($_POST["day1_trip1_segment1_distance"]) ? $_POST["day1_trip1_segment1_distance"] : '99'),
        (!empty($_POST["day1_trip1_segment2_distance"]) ? $_POST["day1_trip1_segment2_distance"] : '99'),
        (!empty($_POST["day1_trip1_segment3_distance"]) ? $_POST["day1_trip1_segment3_distance"] : '99'),
        (!empty($_POST["day1_trip1_segment1_duration"]) ? $_POST["day1_trip1_segment1_duration"] : '99'),
        (!empty($_POST["day1_trip1_segment2_duration"]) ? $_POST["day1_trip1_segment2_duration"] : '99'),
        (!empty($_POST["day1_trip1_segment3_duration"]) ? $_POST["day1_trip1_segment3_duration"] : '99'),
        (!empty($_POST["day1_trip1_segment1_cost"]) ? $_POST["day1_trip1_segment1_cost"] : '99'),
        (!empty($_POST["day1_trip1_segment2_cost"]) ? $_POST["day1_trip1_segment2_cost"] : '99'),
        (!empty($_POST["day1_trip1_segment3_cost"]) ? $_POST["day1_trip1_segment3_cost"] : '99'),
        (!empty($_POST["day1_trip1_segment1_time"]) ? $_POST["day1_trip1_segment1_time"] : '99'),
        (!empty($_POST["day1_trip1_segment2_time"]) ? $_POST["day1_trip1_segment2_time"] : '99'),
        (!empty($_POST["day1_trip1_segment3_time"]) ? $_POST["day1_trip1_segment3_time"] : '99'),

        //day 1 trip 2
        (!empty($_POST["day1_trip2_origin"]) ? $_POST["day1_trip2_origin"] : '99'),
        (!empty($_POST["day1_trip2_destination"]) ? $_POST["day1_trip2_destination"] : '99'),
        (!empty($_POST["day1_trip2_purpose"]) ? $_POST["day1_trip2_purpose"] : '99'),
        (!empty($_POST["day1_trip2_segment1_mode"]) ? $_POST["day1_trip2_segment1_mode"] : '99'),
        (!empty($_POST["day1_trip2_segment2_mode"]) ? $_POST["day1_trip2_segment2_mode"] : '99'),
        (!empty($_POST["day1_trip2_segment3_mode"]) ? $_POST["day1_trip2_segment3_mode"] : '99'),
        (!empty($_POST["day1_trip2_segment1_distance"]) ? $_POST["day1_trip2_segment1_distance"] : '99'),
        (!empty($_POST["day1_trip2_segment2_distance"]) ? $_POST["day1_trip2_segment2_distance"] : '99'),
        (!empty($_POST["day1_trip2_segment3_distance"]) ? $_POST["day1_trip2_segment3_distance"] : '99'),
        (!empty($_POST["day1_trip2_segment1_duration"]) ? $_POST["day1_trip2_segment1_duration"] : '99'),
        (!empty($_POST["day1_trip2_segment2_duration"]) ? $_POST["day1_trip2_segment2_duration"] : '99'),
        (!empty($_POST["day1_trip2_segment3_duration"]) ? $_POST["day1_trip2_segment3_duration"] : '99'),
        (!empty($_POST["day1_trip2_segment1_cost"]) ? $_POST["day1_trip2_segment1_cost"] : '99'),
        (!empty($_POST["day1_trip2_segment2_cost"]) ? $_POST["day1_trip2_segment2_cost"] : '99'),
        (!empty($_POST["day1_trip2_segment3_cost"]) ? $_POST["day1_trip2_segment3_cost"] : '99'),
        (!empty($_POST["day1_trip2_segment1_time"]) ? $_POST["day1_trip2_segment1_time"] : '99'),
        (!empty($_POST["day1_trip2_segment2_time"]) ? $_POST["day1_trip2_segment2_time"] : '99'),
        (!empty($_POST["day1_trip2_segment3_time"]) ? $_POST["day1_trip2_segment3_time"] : '99'),

        //day 1 trip 3
        (!empty($_POST["day1_trip3_origin"]) ? $_POST["day1_trip3_origin"] : '99'),
        (!empty($_POST["day1_trip3_destination"]) ? $_POST["day1_trip3_destination"] : '99'),
        (!empty($_POST["day1_trip3_purpose"]) ? $_POST["day1_trip3_purpose"] : '99'),
        (!empty($_POST["day1_trip3_segment1_mode"]) ? $_POST["day1_trip3_segment1_mode"] : '99'),
        (!empty($_POST["day1_trip3_segment2_mode"]) ? $_POST["day1_trip3_segment2_mode"] : '99'),
        (!empty($_POST["day1_trip3_segment3_mode"]) ? $_POST["day1_trip3_segment3_mode"] : '99'),
        (!empty($_POST["day1_trip3_segment1_distance"]) ? $_POST["day1_trip3_segment1_distance"] : '99'),
        (!empty($_POST["day1_trip3_segment2_distance"]) ? $_POST["day1_trip3_segment2_distance"] : '99'),
        (!empty($_POST["day1_trip3_segment3_distance"]) ? $_POST["day1_trip3_segment3_distance"] : '99'),
        (!empty($_POST["day1_trip3_segment1_duration"]) ? $_POST["day1_trip3_segment1_duration"] : '99'),
        (!empty($_POST["day1_trip3_segment2_duration"]) ? $_POST["day1_trip3_segment2_duration"] : '99'),
        (!empty($_POST["day1_trip3_segment3_duration"]) ? $_POST["day1_trip3_segment3_duration"] : '99'),
        (!empty($_POST["day1_trip3_segment1_cost"]) ? $_POST["day1_trip3_segment1_cost"] : '99'),
        (!empty($_POST["day1_trip3_segment2_cost"]) ? $_POST["day1_trip3_segment2_cost"] : '99'),
        (!empty($_POST["day1_trip3_segment3_cost"]) ? $_POST["day1_trip3_segment3_cost"] : '99'),
        (!empty($_POST["day1_trip3_segment1_time"]) ? $_POST["day1_trip3_segment1_time"] : '99'),
        (!empty($_POST["day1_trip3_segment2_time"]) ? $_POST["day1_trip3_segment2_time"] : '99'),
        (!empty($_POST["day1_trip3_segment3_time"]) ? $_POST["day1_trip3_segment3_time"] : '99'),

        //day 1 trip 4
        (!empty($_POST["day1_trip4_origin"]) ? $_POST["day1_trip4_origin"] : '99'),
        (!empty($_POST["day1_trip4_destination"]) ? $_POST["day1_trip4_destination"] : '99'),
        (!empty($_POST["day1_trip4_purpose"]) ? $_POST["day1_trip4_purpose"] : '99'),
        (!empty($_POST["day1_trip4_segment1_mode"]) ? $_POST["day1_trip4_segment1_mode"] : '99'),
        (!empty($_POST["day1_trip4_segment2_mode"]) ? $_POST["day1_trip4_segment2_mode"] : '99'),
        (!empty($_POST["day1_trip4_segment3_mode"]) ? $_POST["day1_trip4_segment3_mode"] : '99'),
        (!empty($_POST["day1_trip4_segment1_distance"]) ? $_POST["day1_trip4_segment1_distance"] : '99'),
        (!empty($_POST["day1_trip4_segment2_distance"]) ? $_POST["day1_trip4_segment2_distance"] : '99'),
        (!empty($_POST["day1_trip4_segment3_distance"]) ? $_POST["day1_trip4_segment3_distance"] : '99'),
        (!empty($_POST["day1_trip4_segment1_duration"]) ? $_POST["day1_trip4_segment1_duration"] : '99'),
        (!empty($_POST["day1_trip4_segment2_duration"]) ? $_POST["day1_trip4_segment2_duration"] : '99'),
        (!empty($_POST["day1_trip4_segment3_duration"]) ? $_POST["day1_trip4_segment3_duration"] : '99'),
        (!empty($_POST["day1_trip4_segment1_cost"]) ? $_POST["day1_trip4_segment1_cost"] : '99'),
        (!empty($_POST["day1_trip4_segment2_cost"]) ? $_POST["day1_trip4_segment2_cost"] : '99'),
        (!empty($_POST["day1_trip4_segment3_cost"]) ? $_POST["day1_trip4_segment3_cost"] : '99'),
        (!empty($_POST["day1_trip4_segment1_time"]) ? $_POST["day1_trip4_segment1_time"] : '99'),
        (!empty($_POST["day1_trip4_segment2_time"]) ? $_POST["day1_trip4_segment2_time"] : '99'),
        (!empty($_POST["day1_trip4_segment3_time"]) ? $_POST["day1_trip4_segment3_time"] : '99'),

        //day 2 trip 1
        (!empty($_POST["day2_trip1_origin"]) ? $_POST["day2_trip1_origin"] : '99'),
        (!empty($_POST["day2_trip1_destination"]) ? $_POST["day2_trip1_destination"] : '99'),
        (!empty($_POST["day2_trip1_purpose"]) ? $_POST["day2_trip1_purpose"] : '99'),
        (!empty($_POST["day2_trip1_segment1_mode"]) ? $_POST["day2_trip1_segment1_mode"] : '99'),
        (!empty($_POST["day2_trip1_segment2_mode"]) ? $_POST["day2_trip1_segment2_mode"] : '99'),
        (!empty($_POST["day2_trip1_segment3_mode"]) ? $_POST["day2_trip1_segment3_mode"] : '99'),
        (!empty($_POST["day2_trip1_segment1_distance"]) ? $_POST["day2_trip1_segment1_distance"] : '99'),
        (!empty($_POST["day2_trip1_segment2_distance"]) ? $_POST["day2_trip1_segment2_distance"] : '99'),
        (!empty($_POST["day2_trip1_segment3_distance"]) ? $_POST["day2_trip1_segment3_distance"] : '99'),
        (!empty($_POST["day2_trip1_segment1_duration"]) ? $_POST["day2_trip1_segment1_duration"] : '99'),
        (!empty($_POST["day2_trip1_segment2_duration"]) ? $_POST["day2_trip1_segment2_duration"] : '99'),
        (!empty($_POST["day2_trip1_segment3_duration"]) ? $_POST["day2_trip1_segment3_duration"] : '99'),
        (!empty($_POST["day2_trip1_segment1_cost"]) ? $_POST["day2_trip1_segment1_cost"] : '99'),
        (!empty($_POST["day2_trip1_segment2_cost"]) ? $_POST["day2_trip1_segment2_cost"] : '99'),
        (!empty($_POST["day2_trip1_segment3_cost"]) ? $_POST["day2_trip1_segment3_cost"] : '99'),
        (!empty($_POST["day2_trip1_segment1_time"]) ? $_POST["day2_trip1_segment1_time"] : '99'),
        (!empty($_POST["day2_trip1_segment2_time"]) ? $_POST["day2_trip1_segment2_time"] : '99'),
        (!empty($_POST["day2_trip1_segment3_time"]) ? $_POST["day2_trip1_segment3_time"] : '99'),

        //day 2 trip 2
        (!empty($_POST["day2_trip2_origin"]) ? $_POST["day2_trip2_origin"] : '99'),
        (!empty($_POST["day2_trip2_destination"]) ? $_POST["day2_trip2_destination"] : '99'),
        (!empty($_POST["day2_trip2_purpose"]) ? $_POST["day2_trip2_purpose"] : '99'),
        (!empty($_POST["day2_trip2_segment1_mode"]) ? $_POST["day2_trip2_segment1_mode"] : '99'),
        (!empty($_POST["day2_trip2_segment2_mode"]) ? $_POST["day2_trip2_segment2_mode"] : '99'),
        (!empty($_POST["day2_trip2_segment3_mode"]) ? $_POST["day2_trip2_segment3_mode"] : '99'),
        (!empty($_POST["day2_trip2_segment1_distance"]) ? $_POST["day2_trip2_segment1_distance"] : '99'),
        (!empty($_POST["day2_trip2_segment2_distance"]) ? $_POST["day2_trip2_segment2_distance"] : '99'),
        (!empty($_POST["day2_trip2_segment3_distance"]) ? $_POST["day2_trip2_segment3_distance"] : '99'),
        (!empty($_POST["day2_trip2_segment1_duration"]) ? $_POST["day2_trip2_segment1_duration"] : '99'),
        (!empty($_POST["day2_trip2_segment2_duration"]) ? $_POST["day2_trip2_segment2_duration"] : '99'),
        (!empty($_POST["day2_trip2_segment3_duration"]) ? $_POST["day2_trip2_segment3_duration"] : '99'),
        (!empty($_POST["day2_trip2_segment1_cost"]) ? $_POST["day2_trip2_segment1_cost"] : '99'),
        (!empty($_POST["day2_trip2_segment2_cost"]) ? $_POST["day2_trip2_segment2_cost"] : '99'),
        (!empty($_POST["day2_trip2_segment3_cost"]) ? $_POST["day2_trip2_segment3_cost"] : '99'),
        (!empty($_POST["day2_trip2_segment1_time"]) ? $_POST["day2_trip2_segment1_time"] : '99'),
        (!empty($_POST["day2_trip2_segment2_time"]) ? $_POST["day2_trip2_segment2_time"] : '99'),
        (!empty($_POST["day2_trip2_segment3_time"]) ? $_POST["day2_trip2_segment3_time"] : '99'),

        //day 2 trip 3
        (!empty($_POST["day2_trip3_origin"]) ? $_POST["day2_trip3_origin"] : '99'),
        (!empty($_POST["day2_trip3_destination"]) ? $_POST["day2_trip3_destination"] : '99'),
        (!empty($_POST["day2_trip3_purpose"]) ? $_POST["day2_trip3_purpose"] : '99'),
        (!empty($_POST["day2_trip3_segment1_mode"]) ? $_POST["day2_trip3_segment1_mode"] : '99'),
        (!empty($_POST["day2_trip3_segment2_mode"]) ? $_POST["day2_trip3_segment2_mode"] : '99'),
        (!empty($_POST["day2_trip3_segment3_mode"]) ? $_POST["day2_trip3_segment3_mode"] : '99'),
        (!empty($_POST["day2_trip3_segment1_distance"]) ? $_POST["day2_trip3_segment1_distance"] : '99'),
        (!empty($_POST["day2_trip3_segment2_distance"]) ? $_POST["day2_trip3_segment2_distance"] : '99'),
        (!empty($_POST["day2_trip3_segment3_distance"]) ? $_POST["day2_trip3_segment3_distance"] : '99'),
        (!empty($_POST["day2_trip3_segment1_duration"]) ? $_POST["day2_trip3_segment1_duration"] : '99'),
        (!empty($_POST["day2_trip3_segment2_duration"]) ? $_POST["day2_trip3_segment2_duration"] : '99'),
        (!empty($_POST["day2_trip3_segment3_duration"]) ? $_POST["day2_trip3_segment3_duration"] : '99'),
        (!empty($_POST["day2_trip3_segment1_cost"]) ? $_POST["day2_trip3_segment1_cost"] : '99'),
        (!empty($_POST["day2_trip3_segment2_cost"]) ? $_POST["day2_trip3_segment2_cost"] : '99'),
        (!empty($_POST["day2_trip3_segment3_cost"]) ? $_POST["day2_trip3_segment3_cost"] : '99'),
        (!empty($_POST["day2_trip3_segment1_time"]) ? $_POST["day2_trip3_segment1_time"] : '99'),
        (!empty($_POST["day2_trip3_segment2_time"]) ? $_POST["day2_trip3_segment2_time"] : '99'),
        (!empty($_POST["day2_trip3_segment3_time"]) ? $_POST["day2_trip3_segment3_time"] : '99'),

        //day 2 trip 4
        (!empty($_POST["day2_trip4_origin"]) ? $_POST["day2_trip4_origin"] : '99'),
        (!empty($_POST["day2_trip4_destination"]) ? $_POST["day2_trip4_destination"] : '99'),
        (!empty($_POST["day2_trip4_purpose"]) ? $_POST["day2_trip4_purpose"] : '99'),
        (!empty($_POST["day2_trip4_segment1_mode"]) ? $_POST["day2_trip4_segment1_mode"] : '99'),
        (!empty($_POST["day2_trip4_segment2_mode"]) ? $_POST["day2_trip4_segment2_mode"] : '99'),
        (!empty($_POST["day2_trip4_segment3_mode"]) ? $_POST["day2_trip4_segment3_mode"] : '99'),
        (!empty($_POST["day2_trip4_segment1_distance"]) ? $_POST["day2_trip4_segment1_distance"] : '99'),
        (!empty($_POST["day2_trip4_segment2_distance"]) ? $_POST["day2_trip4_segment2_distance"] : '99'),
        (!empty($_POST["day2_trip4_segment3_distance"]) ? $_POST["day2_trip4_segment3_distance"] : '99'),
        (!empty($_POST["day2_trip4_segment1_duration"]) ? $_POST["day2_trip4_segment1_duration"] : '99'),
        (!empty($_POST["day2_trip4_segment2_duration"]) ? $_POST["day2_trip4_segment2_duration"] : '99'),
        (!empty($_POST["day2_trip4_segment3_duration"]) ? $_POST["day2_trip4_segment3_duration"] : '99'),
        (!empty($_POST["day2_trip4_segment1_cost"]) ? $_POST["day2_trip4_segment1_cost"] : '99'),
        (!empty($_POST["day2_trip4_segment2_cost"]) ? $_POST["day2_trip4_segment2_cost"] : '99'),
        (!empty($_POST["day2_trip4_segment3_cost"]) ? $_POST["day2_trip4_segment3_cost"] : '99'),
        (!empty($_POST["day2_trip4_segment1_time"]) ? $_POST["day2_trip4_segment1_time"] : '99'),
        (!empty($_POST["day2_trip4_segment2_time"]) ? $_POST["day2_trip4_segment2_time"] : '99'),
        (!empty($_POST["day2_trip4_segment3_time"]) ? $_POST["day2_trip4_segment3_time"] : '99'),

        //day 3 trip 1
        (!empty($_POST["day3_trip1_origin"]) ? $_POST["day3_trip1_origin"] : '99'),
        (!empty($_POST["day3_trip1_destination"]) ? $_POST["day3_trip1_destination"] : '99'),
        (!empty($_POST["day3_trip1_purpose"]) ? $_POST["day3_trip1_purpose"] : '99'),
        (!empty($_POST["day3_trip1_segment1_mode"]) ? $_POST["day3_trip1_segment1_mode"] : '99'),
        (!empty($_POST["day3_trip1_segment2_mode"]) ? $_POST["day3_trip1_segment2_mode"] : '99'),
        (!empty($_POST["day3_trip1_segment3_mode"]) ? $_POST["day3_trip1_segment3_mode"] : '99'),
        (!empty($_POST["day3_trip1_segment1_distance"]) ? $_POST["day3_trip1_segment1_distance"] : '99'),
        (!empty($_POST["day3_trip1_segment2_distance"]) ? $_POST["day3_trip1_segment2_distance"] : '99'),
        (!empty($_POST["day3_trip1_segment3_distance"]) ? $_POST["day3_trip1_segment3_distance"] : '99'),
        (!empty($_POST["day3_trip1_segment1_duration"]) ? $_POST["day3_trip1_segment1_duration"] : '99'),
        (!empty($_POST["day3_trip1_segment2_duration"]) ? $_POST["day3_trip1_segment2_duration"] : '99'),
        (!empty($_POST["day3_trip1_segment3_duration"]) ? $_POST["day3_trip1_segment3_duration"] : '99'),
        (!empty($_POST["day3_trip1_segment1_cost"]) ? $_POST["day3_trip1_segment1_cost"] : '99'),
        (!empty($_POST["day3_trip1_segment2_cost"]) ? $_POST["day3_trip1_segment2_cost"] : '99'),
        (!empty($_POST["day3_trip1_segment3_cost"]) ? $_POST["day3_trip1_segment3_cost"] : '99'),
        (!empty($_POST["day3_trip1_segment1_time"]) ? $_POST["day3_trip1_segment1_time"] : '99'),
        (!empty($_POST["day3_trip1_segment2_time"]) ? $_POST["day3_trip1_segment2_time"] : '99'),
        (!empty($_POST["day3_trip1_segment3_time"]) ? $_POST["day3_trip1_segment3_time"] : '99'),

        //day 3 trip 2
        (!empty($_POST["day3_trip2_origin"]) ? $_POST["day3_trip2_origin"] : '99'),
        (!empty($_POST["day3_trip2_destination"]) ? $_POST["day3_trip2_destination"] : '99'),
        (!empty($_POST["day3_trip2_purpose"]) ? $_POST["day3_trip2_purpose"] : '99'),
        (!empty($_POST["day3_trip2_segment1_mode"]) ? $_POST["day3_trip2_segment1_mode"] : '99'),
        (!empty($_POST["day3_trip2_segment2_mode"]) ? $_POST["day3_trip2_segment2_mode"] : '99'),
        (!empty($_POST["day3_trip2_segment3_mode"]) ? $_POST["day3_trip2_segment3_mode"] : '99'),
        (!empty($_POST["day3_trip2_segment1_distance"]) ? $_POST["day3_trip2_segment1_distance"] : '99'),
        (!empty($_POST["day3_trip2_segment2_distance"]) ? $_POST["day3_trip2_segment2_distance"] : '99'),
        (!empty($_POST["day3_trip2_segment3_distance"]) ? $_POST["day3_trip2_segment3_distance"] : '99'),
        (!empty($_POST["day3_trip2_segment1_duration"]) ? $_POST["day3_trip2_segment1_duration"] : '99'),
        (!empty($_POST["day3_trip2_segment2_duration"]) ? $_POST["day3_trip2_segment2_duration"] : '99'),
        (!empty($_POST["day3_trip2_segment3_duration"]) ? $_POST["day3_trip2_segment3_duration"] : '99'),
        (!empty($_POST["day3_trip2_segment1_cost"]) ? $_POST["day3_trip2_segment1_cost"] : '99'),
        (!empty($_POST["day3_trip2_segment2_cost"]) ? $_POST["day3_trip2_segment2_cost"] : '99'),
        (!empty($_POST["day3_trip2_segment3_cost"]) ? $_POST["day3_trip2_segment3_cost"] : '99'),
        (!empty($_POST["day3_trip2_segment1_time"]) ? $_POST["day3_trip2_segment1_time"] : '99'),
        (!empty($_POST["day3_trip2_segment2_time"]) ? $_POST["day3_trip2_segment2_time"] : '99'),
        (!empty($_POST["day3_trip2_segment3_time"]) ? $_POST["day3_trip2_segment3_time"] : '99'),

        //day 3 trip 3
        (!empty($_POST["day3_trip3_origin"]) ? $_POST["day3_trip3_origin"] : '99'),
        (!empty($_POST["day3_trip3_destination"]) ? $_POST["day3_trip3_destination"] : '99'),
        (!empty($_POST["day3_trip3_purpose"]) ? $_POST["day3_trip3_purpose"] : '99'),
        (!empty($_POST["day3_trip3_segment1_mode"]) ? $_POST["day3_trip3_segment1_mode"] : '99'),
        (!empty($_POST["day3_trip3_segment2_mode"]) ? $_POST["day3_trip3_segment2_mode"] : '99'),
        (!empty($_POST["day3_trip3_segment3_mode"]) ? $_POST["day3_trip3_segment3_mode"] : '99'),
        (!empty($_POST["day3_trip3_segment1_distance"]) ? $_POST["day3_trip3_segment1_distance"] : '99'),
        (!empty($_POST["day3_trip3_segment2_distance"]) ? $_POST["day3_trip3_segment2_distance"] : '99'),
        (!empty($_POST["day3_trip3_segment3_distance"]) ? $_POST["day3_trip3_segment3_distance"] : '99'),
        (!empty($_POST["day3_trip3_segment1_duration"]) ? $_POST["day3_trip3_segment1_duration"] : '99'),
        (!empty($_POST["day3_trip3_segment2_duration"]) ? $_POST["day3_trip3_segment2_duration"] : '99'),
        (!empty($_POST["day3_trip3_segment3_duration"]) ? $_POST["day3_trip3_segment3_duration"] : '99'),
        (!empty($_POST["day3_trip3_segment1_cost"]) ? $_POST["day3_trip3_segment1_cost"] : '99'),
        (!empty($_POST["day3_trip3_segment2_cost"]) ? $_POST["day3_trip3_segment2_cost"] : '99'),
        (!empty($_POST["day3_trip3_segment3_cost"]) ? $_POST["day3_trip3_segment3_cost"] : '99'),
        (!empty($_POST["day3_trip3_segment1_time"]) ? $_POST["day3_trip3_segment1_time"] : '99'),
        (!empty($_POST["day3_trip3_segment2_time"]) ? $_POST["day3_trip3_segment2_time"] : '99'),
        (!empty($_POST["day3_trip3_segment3_time"]) ? $_POST["day3_trip3_segment3_time"] : '99'),

        //day 3 trip 4
        (!empty($_POST["day3_trip4_origin"]) ? $_POST["day3_trip4_origin"] : '99'),
        (!empty($_POST["day3_trip4_destination"]) ? $_POST["day3_trip4_destination"] : '99'),
        (!empty($_POST["day3_trip4_purpose"]) ? $_POST["day3_trip4_purpose"] : '99'),
        (!empty($_POST["day3_trip4_segment1_mode"]) ? $_POST["day3_trip4_segment1_mode"] : '99'),
        (!empty($_POST["day3_trip4_segment2_mode"]) ? $_POST["day3_trip4_segment2_mode"] : '99'),
        (!empty($_POST["day3_trip4_segment3_mode"]) ? $_POST["day3_trip4_segment3_mode"] : '99'),
        (!empty($_POST["day3_trip4_segment1_distance"]) ? $_POST["day3_trip4_segment1_distance"] : '99'),
        (!empty($_POST["day3_trip4_segment2_distance"]) ? $_POST["day3_trip4_segment2_distance"] : '99'),
        (!empty($_POST["day3_trip4_segment3_distance"]) ? $_POST["day3_trip4_segment3_distance"] : '99'),
        (!empty($_POST["day3_trip4_segment1_duration"]) ? $_POST["day3_trip4_segment1_duration"] : '99'),
        (!empty($_POST["day3_trip4_segment2_duration"]) ? $_POST["day3_trip4_segment2_duration"] : '99'),
        (!empty($_POST["day3_trip4_segment3_duration"]) ? $_POST["day3_trip4_segment3_duration"] : '99'),
        (!empty($_POST["day3_trip4_segment1_cost"]) ? $_POST["day3_trip4_segment1_cost"] : '99'),
        (!empty($_POST["day3_trip4_segment2_cost"]) ? $_POST["day3_trip4_segment2_cost"] : '99'),
        (!empty($_POST["day3_trip4_segment3_cost"]) ? $_POST["day3_trip4_segment3_cost"] : '99'),
        (!empty($_POST["day3_trip4_segment1_time"]) ? $_POST["day3_trip4_segment1_time"] : '99'),
        (!empty($_POST["day3_trip4_segment2_time"]) ? $_POST["day3_trip4_segment2_time"] : '99'),
        (!empty($_POST["day3_trip4_segment3_time"]) ? $_POST["day3_trip4_segment3_time"] : '99'),
        
        //day 4 trip 1
        (!empty($_POST["day4_trip1_origin"]) ? $_POST["day4_trip1_origin"] : '99'),
        (!empty($_POST["day4_trip1_destination"]) ? $_POST["day4_trip1_destination"] : '99'),
        (!empty($_POST["day4_trip1_purpose"]) ? $_POST["day4_trip1_purpose"] : '99'),
        (!empty($_POST["day4_trip1_segment1_mode"]) ? $_POST["day4_trip1_segment1_mode"] : '99'),
        (!empty($_POST["day4_trip1_segment2_mode"]) ? $_POST["day4_trip1_segment2_mode"] : '99'),
        (!empty($_POST["day4_trip1_segment3_mode"]) ? $_POST["day4_trip1_segment3_mode"] : '99'),
        (!empty($_POST["day4_trip1_segment1_distance"]) ? $_POST["day4_trip1_segment1_distance"] : '99'),
        (!empty($_POST["day4_trip1_segment2_distance"]) ? $_POST["day4_trip1_segment2_distance"] : '99'),
        (!empty($_POST["day4_trip1_segment3_distance"]) ? $_POST["day4_trip1_segment3_distance"] : '99'),
        (!empty($_POST["day4_trip1_segment1_duration"]) ? $_POST["day4_trip1_segment1_duration"] : '99'),
        (!empty($_POST["day4_trip1_segment2_duration"]) ? $_POST["day4_trip1_segment2_duration"] : '99'),
        (!empty($_POST["day4_trip1_segment3_duration"]) ? $_POST["day4_trip1_segment3_duration"] : '99'),
        (!empty($_POST["day4_trip1_segment1_cost"]) ? $_POST["day4_trip1_segment1_cost"] : '99'),
        (!empty($_POST["day4_trip1_segment2_cost"]) ? $_POST["day4_trip1_segment2_cost"] : '99'),
        (!empty($_POST["day4_trip1_segment3_cost"]) ? $_POST["day4_trip1_segment3_cost"] : '99'),
        (!empty($_POST["day4_trip1_segment1_time"]) ? $_POST["day4_trip1_segment1_time"] : '99'),
        (!empty($_POST["day4_trip1_segment2_time"]) ? $_POST["day4_trip1_segment2_time"] : '99'),
        (!empty($_POST["day4_trip1_segment3_time"]) ? $_POST["day4_trip1_segment3_time"] : '99'),

        //day 4 trip 2
        (!empty($_POST["day4_trip2_origin"]) ? $_POST["day4_trip2_origin"] : '99'),
        (!empty($_POST["day4_trip2_destination"]) ? $_POST["day4_trip2_destination"] : '99'),
        (!empty($_POST["day4_trip2_purpose"]) ? $_POST["day4_trip2_purpose"] : '99'),
        (!empty($_POST["day4_trip2_segment1_mode"]) ? $_POST["day4_trip2_segment1_mode"] : '99'),
        (!empty($_POST["day4_trip2_segment2_mode"]) ? $_POST["day4_trip2_segment1_mode"] : '99'),
        (!empty($_POST["day4_trip2_segment3_mode"]) ? $_POST["day4_trip2_segment1_mode"] : '99'),
        (!empty($_POST["day4_trip2_segment1_distance"]) ? $_POST["day4_trip2_segment1_distance"] : '99'),
        (!empty($_POST["day4_trip2_segment2_distance"]) ? $_POST["day4_trip2_segment2_distance"] : '99'),
        (!empty($_POST["day4_trip2_segment3_distance"]) ? $_POST["day4_trip2_segment3_distance"] : '99'),
        (!empty($_POST["day4_trip2_segment1_duration"]) ? $_POST["day4_trip2_segment1_duration"] : '99'),
        (!empty($_POST["day4_trip2_segment2_duration"]) ? $_POST["day4_trip2_segment2_duration"] : '99'),
        (!empty($_POST["day4_trip2_segment3_duration"]) ? $_POST["day4_trip2_segment3_duration"] : '99'),
        (!empty($_POST["day4_trip2_segment1_cost"]) ? $_POST["day4_trip2_segment1_cost"] : '99'),
        (!empty($_POST["day4_trip2_segment2_cost"]) ? $_POST["day4_trip2_segment2_cost"] : '99'),
        (!empty($_POST["day4_trip2_segment3_cost"]) ? $_POST["day4_trip2_segment3_cost"] : '99'),
        (!empty($_POST["day4_trip2_segment1_time"]) ? $_POST["day4_trip2_segment1_time"] : '99'),
        (!empty($_POST["day4_trip2_segment2_time"]) ? $_POST["day4_trip2_segment2_time"] : '99'),
        (!empty($_POST["day4_trip2_segment3_time"]) ? $_POST["day4_trip2_segment3_time"] : '99'),

        //day 4 trip 3
        (!empty($_POST["day4_trip3_origin"]) ? $_POST["day4_trip3_origin"] : '99'),
        (!empty($_POST["day4_trip3_destination"]) ? $_POST["day4_trip3_destination"] : '99'),
        (!empty($_POST["day4_trip3_purpose"]) ? $_POST["day4_trip3_purpose"] : '99'),
        (!empty($_POST["day4_trip3_segment1_mode"]) ? $_POST["day4_trip3_segment1_mode"] : '99'),
        (!empty($_POST["day4_trip3_segment2_mode"]) ? $_POST["day4_trip3_segment1_mode"] : '99'),
        (!empty($_POST["day4_trip3_segment3_mode"]) ? $_POST["day4_trip3_segment1_mode"] : '99'),
        (!empty($_POST["day4_trip3_segment1_distance"]) ? $_POST["day4_trip3_segment1_distance"] : '99'),
        (!empty($_POST["day4_trip3_segment2_distance"]) ? $_POST["day4_trip3_segment2_distance"] : '99'),
        (!empty($_POST["day4_trip3_segment3_distance"]) ? $_POST["day4_trip3_segment3_distance"] : '99'),
        (!empty($_POST["day4_trip3_segment1_duration"]) ? $_POST["day4_trip3_segment1_duration"] : '99'),
        (!empty($_POST["day4_trip3_segment2_duration"]) ? $_POST["day4_trip3_segment2_duration"] : '99'),
        (!empty($_POST["day4_trip3_segment3_duration"]) ? $_POST["day4_trip3_segment3_duration"] : '99'),
        (!empty($_POST["day4_trip3_segment1_cost"]) ? $_POST["day4_trip3_segment1_cost"] : '99'),
        (!empty($_POST["day4_trip3_segment2_cost"]) ? $_POST["day4_trip3_segment2_cost"] : '99'),
        (!empty($_POST["day4_trip3_segment3_cost"]) ? $_POST["day4_trip3_segment3_cost"] : '99'),
        (!empty($_POST["day4_trip3_segment1_time"]) ? $_POST["day4_trip3_segment1_time"] : '99'),
        (!empty($_POST["day4_trip3_segment2_time"]) ? $_POST["day4_trip3_segment2_time"] : '99'),
        (!empty($_POST["day4_trip3_segment3_time"]) ? $_POST["day4_trip3_segment3_time"] : '99'),

        //day 4 trip 4
        (!empty($_POST["day4_trip4_origin"]) ? $_POST["day4_trip4_origin"] : '99'),
        (!empty($_POST["day4_trip4_destination"]) ? $_POST["day4_trip4_destination"] : '99'),
        (!empty($_POST["day4_trip4_purpose"]) ? $_POST["day4_trip4_purpose"] : '99'),
        (!empty($_POST["day4_trip4_segment1_mode"]) ? $_POST["day4_trip4_segment1_mode"] : '99'),
        (!empty($_POST["day4_trip4_segment2_mode"]) ? $_POST["day4_trip4_segment1_mode"] : '99'),
        (!empty($_POST["day4_trip4_segment3_mode"]) ? $_POST["day4_trip4_segment1_mode"] : '99'),
        (!empty($_POST["day4_trip4_segment1_distance"]) ? $_POST["day4_trip4_segment1_distance"] : '99'),
        (!empty($_POST["day4_trip4_segment2_distance"]) ? $_POST["day4_trip4_segment2_distance"] : '99'),
        (!empty($_POST["day4_trip4_segment3_distance"]) ? $_POST["day4_trip4_segment3_distance"] : '99'),
        (!empty($_POST["day4_trip4_segment1_duration"]) ? $_POST["day4_trip4_segment1_duration"] : '99'),
        (!empty($_POST["day4_trip4_segment2_duration"]) ? $_POST["day4_trip4_segment2_duration"] : '99'),
        (!empty($_POST["day4_trip4_segment3_duration"]) ? $_POST["day4_trip4_segment3_duration"] : '99'),
        (!empty($_POST["day4_trip4_segment1_cost"]) ? $_POST["day4_trip4_segment1_cost"] : '99'),
        (!empty($_POST["day4_trip4_segment2_cost"]) ? $_POST["day4_trip4_segment2_cost"] : '99'),
        (!empty($_POST["day4_trip4_segment3_cost"]) ? $_POST["day4_trip4_segment3_cost"] : '99'),
        (!empty($_POST["day4_trip4_segment1_time"]) ? $_POST["day4_trip4_segment1_time"] : '99'),
        (!empty($_POST["day4_trip4_segment2_time"]) ? $_POST["day4_trip4_segment2_time"] : '99'),
        (!empty($_POST["day4_trip4_segment3_time"]) ? $_POST["day4_trip4_segment3_time"] : '99'),
        
        //day 5 trip 1
        (!empty($_POST["day5_trip1_origin"]) ? $_POST["day5_trip1_origin"] : '99'),
        (!empty($_POST["day5_trip1_destination"]) ? $_POST["day5_trip1_destination"] : '99'),
        (!empty($_POST["day5_trip1_purpose"]) ? $_POST["day5_trip1_purpose"] : '99'),
        (!empty($_POST["day5_trip1_segment1_mode"]) ? $_POST["day5_trip1_segment1_mode"] : '99'),
        (!empty($_POST["day5_trip1_segment2_mode"]) ? $_POST["day5_trip1_segment1_mode"] : '99'),
        (!empty($_POST["day5_trip1_segment3_mode"]) ? $_POST["day5_trip1_segment1_mode"] : '99'),
        (!empty($_POST["day5_trip1_segment1_distance"]) ? $_POST["day5_trip1_segment1_distance"] : '99'),
        (!empty($_POST["day5_trip1_segment2_distance"]) ? $_POST["day5_trip1_segment2_distance"] : '99'),
        (!empty($_POST["day5_trip1_segment3_distance"]) ? $_POST["day5_trip1_segment3_distance"] : '99'),
        (!empty($_POST["day5_trip1_segment1_duration"]) ? $_POST["day5_trip1_segment1_duration"] : '99'),
        (!empty($_POST["day5_trip1_segment2_duration"]) ? $_POST["day5_trip1_segment2_duration"] : '99'),
        (!empty($_POST["day5_trip1_segment3_duration"]) ? $_POST["day5_trip1_segment3_duration"] : '99'),
        (!empty($_POST["day5_trip1_segment1_cost"]) ? $_POST["day5_trip1_segment1_cost"] : '99'),
        (!empty($_POST["day5_trip1_segment2_cost"]) ? $_POST["day5_trip1_segment2_cost"] : '99'),
        (!empty($_POST["day5_trip1_segment3_cost"]) ? $_POST["day5_trip1_segment3_cost"] : '99'),
        (!empty($_POST["day5_trip1_segment1_time"]) ? $_POST["day5_trip1_segment1_time"] : '99'),
        (!empty($_POST["day5_trip1_segment2_time"]) ? $_POST["day5_trip1_segment2_time"] : '99'),
        (!empty($_POST["day5_trip1_segment3_time"]) ? $_POST["day5_trip1_segment3_time"] : '99'),

        //day 5 trip 2
        (!empty($_POST["day5_trip2_origin"]) ? $_POST["day5_trip2_origin"] : '99'),
        (!empty($_POST["day5_trip2_destination"]) ? $_POST["day5_trip2_destination"] : '99'),
        (!empty($_POST["day5_trip2_purpose"]) ? $_POST["day5_trip2_purpose"] : '99'),
        (!empty($_POST["day5_trip2_segment1_mode"]) ? $_POST["day5_trip2_segment1_mode"] : '99'),
        (!empty($_POST["day5_trip2_segment2_mode"]) ? $_POST["day5_trip2_segment1_mode"] : '99'),
        (!empty($_POST["day5_trip2_segment3_mode"]) ? $_POST["day5_trip2_segment1_mode"] : '99'),
        (!empty($_POST["day5_trip2_segment1_distance"]) ? $_POST["day5_trip2_segment1_distance"] : '99'),
        (!empty($_POST["day5_trip2_segment2_distance"]) ? $_POST["day5_trip2_segment2_distance"] : '99'),
        (!empty($_POST["day5_trip2_segment3_distance"]) ? $_POST["day5_trip2_segment3_distance"] : '99'),
        (!empty($_POST["day5_trip2_segment1_duration"]) ? $_POST["day5_trip2_segment1_duration"] : '99'),
        (!empty($_POST["day5_trip2_segment2_duration"]) ? $_POST["day5_trip2_segment2_duration"] : '99'),
        (!empty($_POST["day5_trip2_segment3_duration"]) ? $_POST["day5_trip2_segment3_duration"] : '99'),
        (!empty($_POST["day5_trip2_segment1_cost"]) ? $_POST["day5_trip2_segment1_cost"] : '99'),
        (!empty($_POST["day5_trip2_segment2_cost"]) ? $_POST["day5_trip2_segment2_cost"] : '99'),
        (!empty($_POST["day5_trip2_segment3_cost"]) ? $_POST["day5_trip2_segment3_cost"] : '99'),
        (!empty($_POST["day5_trip2_segment1_time"]) ? $_POST["day5_trip2_segment1_time"] : '99'),
        (!empty($_POST["day5_trip2_segment2_time"]) ? $_POST["day5_trip2_segment2_time"] : '99'),
        (!empty($_POST["day5_trip2_segment3_time"]) ? $_POST["day5_trip2_segment3_time"] : '99'),

        //day 5 trip 3
        (!empty($_POST["day5_trip3_origin"]) ? $_POST["day5_trip3_origin"] : '99'),
        (!empty($_POST["day5_trip3_destination"]) ? $_POST["day5_trip3_destination"] : '99'),
        (!empty($_POST["day5_trip3_purpose"]) ? $_POST["day5_trip3_purpose"] : '99'),
        (!empty($_POST["day5_trip3_segment1_mode"]) ? $_POST["day5_trip3_segment1_mode"] : '99'),
        (!empty($_POST["day5_trip3_segment2_mode"]) ? $_POST["day5_trip3_segment1_mode"] : '99'),
        (!empty($_POST["day5_trip3_segment3_mode"]) ? $_POST["day5_trip3_segment1_mode"] : '99'),
        (!empty($_POST["day5_trip3_segment1_distance"]) ? $_POST["day5_trip3_segment1_distance"] : '99'),
        (!empty($_POST["day5_trip3_segment2_distance"]) ? $_POST["day5_trip3_segment2_distance"] : '99'),
        (!empty($_POST["day5_trip3_segment3_distance"]) ? $_POST["day5_trip3_segment3_distance"] : '99'),
        (!empty($_POST["day5_trip3_segment1_duration"]) ? $_POST["day5_trip3_segment1_duration"] : '99'),
        (!empty($_POST["day5_trip3_segment2_duration"]) ? $_POST["day5_trip3_segment2_duration"] : '99'),
        (!empty($_POST["day5_trip3_segment3_duration"]) ? $_POST["day5_trip3_segment3_duration"] : '99'),
        (!empty($_POST["day5_trip3_segment1_cost"]) ? $_POST["day5_trip3_segment1_cost"] : '99'),
        (!empty($_POST["day5_trip3_segment2_cost"]) ? $_POST["day5_trip3_segment2_cost"] : '99'),
        (!empty($_POST["day5_trip3_segment3_cost"]) ? $_POST["day5_trip3_segment3_cost"] : '99'),
        (!empty($_POST["day5_trip3_segment1_time"]) ? $_POST["day5_trip3_segment1_time"] : '99'),
        (!empty($_POST["day5_trip3_segment2_time"]) ? $_POST["day5_trip3_segment2_time"] : '99'),
        (!empty($_POST["day5_trip3_segment3_time"]) ? $_POST["day5_trip3_segment3_time"] : '99'),

        //day 5 trip 4
        (!empty($_POST["day5_trip4_origin"]) ? $_POST["day5_trip4_origin"] : '99'),
        (!empty($_POST["day5_trip4_destination"]) ? $_POST["day5_trip4_destination"] : '99'),
        (!empty($_POST["day5_trip4_purpose"]) ? $_POST["day5_trip4_purpose"] : '99'),
        (!empty($_POST["day5_trip4_segment1_mode"]) ? $_POST["day5_trip4_segment1_mode"] : '99'),
        (!empty($_POST["day5_trip4_segment2_mode"]) ? $_POST["day5_trip4_segment1_mode"] : '99'),
        (!empty($_POST["day5_trip4_segment3_mode"]) ? $_POST["day5_trip4_segment1_mode"] : '99'),
        (!empty($_POST["day5_trip4_segment1_distance"]) ? $_POST["day5_trip4_segment1_distance"] : '99'),
        (!empty($_POST["day5_trip4_segment2_distance"]) ? $_POST["day5_trip4_segment2_distance"] : '99'),
        (!empty($_POST["day5_trip4_segment3_distance"]) ? $_POST["day5_trip4_segment3_distance"] : '99'),
        (!empty($_POST["day5_trip4_segment1_duration"]) ? $_POST["day5_trip4_segment1_duration"] : '99'),
        (!empty($_POST["day5_trip4_segment2_duration"]) ? $_POST["day5_trip4_segment2_duration"] : '99'),
        (!empty($_POST["day5_trip4_segment3_duration"]) ? $_POST["day5_trip4_segment3_duration"] : '99'),
        (!empty($_POST["day5_trip4_segment1_cost"]) ? $_POST["day5_trip4_segment1_cost"] : '99'),
        (!empty($_POST["day5_trip4_segment2_cost"]) ? $_POST["day5_trip4_segment2_cost"] : '99'),
        (!empty($_POST["day5_trip4_segment3_cost"]) ? $_POST["day5_trip4_segment3_cost"] : '99'),
        (!empty($_POST["day5_trip4_segment1_time"]) ? $_POST["day5_trip4_segment1_time"] : '99'),
        (!empty($_POST["day5_trip4_segment2_time"]) ? $_POST["day5_trip4_segment2_time"] : '99'),
        (!empty($_POST["day5_trip4_segment3_time"]) ? $_POST["day5_trip4_segment3_time"] : '99'),
        
        //day 6 trip 1
        (!empty($_POST["day6_trip1_origin"]) ? $_POST["day6_trip1_origin"] : '99'),
        (!empty($_POST["day6_trip1_destination"]) ? $_POST["day6_trip1_destination"] : '99'),
        (!empty($_POST["day6_trip1_purpose"]) ? $_POST["day6_trip1_purpose"] : '99'),
        (!empty($_POST["day6_trip1_segment1_mode"]) ? $_POST["day6_trip1_segment1_mode"] : '99'),
        (!empty($_POST["day6_trip1_segment2_mode"]) ? $_POST["day6_trip1_segment1_mode"] : '99'),
        (!empty($_POST["day6_trip1_segment3_mode"]) ? $_POST["day6_trip1_segment1_mode"] : '99'),
        (!empty($_POST["day6_trip1_segment1_distance"]) ? $_POST["day6_trip1_segment1_distance"] : '99'),
        (!empty($_POST["day6_trip1_segment2_distance"]) ? $_POST["day6_trip1_segment2_distance"] : '99'),
        (!empty($_POST["day6_trip1_segment3_distance"]) ? $_POST["day6_trip1_segment3_distance"] : '99'),
        (!empty($_POST["day6_trip1_segment1_duration"]) ? $_POST["day6_trip1_segment1_duration"] : '99'),
        (!empty($_POST["day6_trip1_segment2_duration"]) ? $_POST["day6_trip1_segment2_duration"] : '99'),
        (!empty($_POST["day6_trip1_segment3_duration"]) ? $_POST["day6_trip1_segment3_duration"] : '99'),
        (!empty($_POST["day6_trip1_segment1_cost"]) ? $_POST["day6_trip1_segment1_cost"] : '99'),
        (!empty($_POST["day6_trip1_segment2_cost"]) ? $_POST["day6_trip1_segment2_cost"] : '99'),
        (!empty($_POST["day6_trip1_segment3_cost"]) ? $_POST["day6_trip1_segment3_cost"] : '99'),
        (!empty($_POST["day6_trip1_segment1_time"]) ? $_POST["day6_trip1_segment1_time"] : '99'),
        (!empty($_POST["day6_trip1_segment2_time"]) ? $_POST["day6_trip1_segment2_time"] : '99'),
        (!empty($_POST["day6_trip1_segment3_time"]) ? $_POST["day6_trip1_segment3_time"] : '99'),

        //day 6 trip 2
        (!empty($_POST["day6_trip2_origin"]) ? $_POST["day6_trip2_origin"] : '99'),
        (!empty($_POST["day6_trip2_destination"]) ? $_POST["day6_trip2_destination"] : '99'),
        (!empty($_POST["day6_trip2_purpose"]) ? $_POST["day6_trip2_purpose"] : '99'),
        (!empty($_POST["day6_trip2_segment1_mode"]) ? $_POST["day6_trip2_segment1_mode"] : '99'),
        (!empty($_POST["day6_trip2_segment2_mode"]) ? $_POST["day6_trip2_segment1_mode"] : '99'),
        (!empty($_POST["day6_trip2_segment3_mode"]) ? $_POST["day6_trip2_segment1_mode"] : '99'),
        (!empty($_POST["day6_trip2_segment1_distance"]) ? $_POST["day6_trip2_segment1_distance"] : '99'),
        (!empty($_POST["day6_trip2_segment2_distance"]) ? $_POST["day6_trip2_segment2_distance"] : '99'),
        (!empty($_POST["day6_trip2_segment3_distance"]) ? $_POST["day6_trip2_segment3_distance"] : '99'),
        (!empty($_POST["day6_trip2_segment1_duration"]) ? $_POST["day6_trip2_segment1_duration"] : '99'),
        (!empty($_POST["day6_trip2_segment2_duration"]) ? $_POST["day6_trip2_segment2_duration"] : '99'),
        (!empty($_POST["day6_trip2_segment3_duration"]) ? $_POST["day6_trip2_segment3_duration"] : '99'),
        (!empty($_POST["day6_trip2_segment1_cost"]) ? $_POST["day6_trip2_segment1_cost"] : '99'),
        (!empty($_POST["day6_trip2_segment2_cost"]) ? $_POST["day6_trip2_segment2_cost"] : '99'),
        (!empty($_POST["day6_trip2_segment3_cost"]) ? $_POST["day6_trip2_segment3_cost"] : '99'),
        (!empty($_POST["day6_trip2_segment1_time"]) ? $_POST["day6_trip2_segment1_time"] : '99'),
        (!empty($_POST["day6_trip2_segment2_time"]) ? $_POST["day6_trip2_segment2_time"] : '99'),
        (!empty($_POST["day6_trip2_segment3_time"]) ? $_POST["day6_trip2_segment3_time"] : '99'),

        //day 6 trip 3
        (!empty($_POST["day6_trip3_origin"]) ? $_POST["day6_trip3_origin"] : '99'),
        (!empty($_POST["day6_trip3_destination"]) ? $_POST["day6_trip3_destination"] : '99'),
        (!empty($_POST["day6_trip3_purpose"]) ? $_POST["day6_trip3_purpose"] : '99'),
        (!empty($_POST["day6_trip3_segment1_mode"]) ? $_POST["day6_trip3_segment1_mode"] : '99'),
        (!empty($_POST["day6_trip3_segment2_mode"]) ? $_POST["day6_trip3_segment1_mode"] : '99'),
        (!empty($_POST["day6_trip3_segment3_mode"]) ? $_POST["day6_trip3_segment1_mode"] : '99'),
        (!empty($_POST["day6_trip3_segment1_distance"]) ? $_POST["day6_trip3_segment1_distance"] : '99'),
        (!empty($_POST["day6_trip3_segment2_distance"]) ? $_POST["day6_trip3_segment2_distance"] : '99'),
        (!empty($_POST["day6_trip3_segment3_distance"]) ? $_POST["day6_trip3_segment3_distance"] : '99'),
        (!empty($_POST["day6_trip3_segment1_duration"]) ? $_POST["day6_trip3_segment1_duration"] : '99'),
        (!empty($_POST["day6_trip3_segment2_duration"]) ? $_POST["day6_trip3_segment2_duration"] : '99'),
        (!empty($_POST["day6_trip3_segment3_duration"]) ? $_POST["day6_trip3_segment3_duration"] : '99'),
        (!empty($_POST["day6_trip3_segment1_cost"]) ? $_POST["day6_trip3_segment1_cost"] : '99'),
        (!empty($_POST["day6_trip3_segment2_cost"]) ? $_POST["day6_trip3_segment2_cost"] : '99'),
        (!empty($_POST["day6_trip3_segment3_cost"]) ? $_POST["day6_trip3_segment3_cost"] : '99'),
        (!empty($_POST["day6_trip3_segment1_time"]) ? $_POST["day6_trip3_segment1_time"] : '99'),
        (!empty($_POST["day6_trip3_segment2_time"]) ? $_POST["day6_trip3_segment2_time"] : '99'),
        (!empty($_POST["day6_trip3_segment3_time"]) ? $_POST["day6_trip3_segment3_time"] : '99'),

        //day 6 trip 4
        (!empty($_POST["day6_trip4_origin"]) ? $_POST["day6_trip4_origin"] : '99'),
        (!empty($_POST["day6_trip4_destination"]) ? $_POST["day6_trip4_destination"] : '99'),
        (!empty($_POST["day6_trip4_purpose"]) ? $_POST["day6_trip4_purpose"] : '99'),
        (!empty($_POST["day6_trip4_segment1_mode"]) ? $_POST["day6_trip4_segment1_mode"] : '99'),
        (!empty($_POST["day6_trip4_segment2_mode"]) ? $_POST["day6_trip4_segment1_mode"] : '99'),
        (!empty($_POST["day6_trip4_segment3_mode"]) ? $_POST["day6_trip4_segment1_mode"] : '99'),
        (!empty($_POST["day6_trip4_segment1_distance"]) ? $_POST["day6_trip4_segment1_distance"] : '99'),
        (!empty($_POST["day6_trip4_segment2_distance"]) ? $_POST["day6_trip4_segment2_distance"] : '99'),
        (!empty($_POST["day6_trip4_segment3_distance"]) ? $_POST["day6_trip4_segment3_distance"] : '99'),
        (!empty($_POST["day6_trip4_segment1_duration"]) ? $_POST["day6_trip4_segment1_duration"] : '99'),
        (!empty($_POST["day6_trip4_segment2_duration"]) ? $_POST["day6_trip4_segment2_duration"] : '99'),
        (!empty($_POST["day6_trip4_segment3_duration"]) ? $_POST["day6_trip4_segment3_duration"] : '99'),
        (!empty($_POST["day6_trip4_segment1_cost"]) ? $_POST["day6_trip4_segment1_cost"] : '99'),
        (!empty($_POST["day6_trip4_segment2_cost"]) ? $_POST["day6_trip4_segment2_cost"] : '99'),
        (!empty($_POST["day6_trip4_segment3_cost"]) ? $_POST["day6_trip4_segment3_cost"] : '99'),
        (!empty($_POST["day6_trip4_segment1_time"]) ? $_POST["day6_trip4_segment1_time"] : '99'),
        (!empty($_POST["day6_trip4_segment2_time"]) ? $_POST["day6_trip4_segment2_time"] : '99'),
        (!empty($_POST["day6_trip4_segment3_time"]) ? $_POST["day6_trip4_segment3_time"] : '99'),
        
        //day 7 trip 1
        (!empty($_POST["day7_trip1_origin"]) ? $_POST["day7_trip1_origin"] : '99'),
        (!empty($_POST["day7_trip1_destination"]) ? $_POST["day7_trip1_destination"] : '99'),
        (!empty($_POST["day7_trip1_purpose"]) ? $_POST["day7_trip1_purpose"] : '99'),
        (!empty($_POST["day7_trip1_segment1_mode"]) ? $_POST["day7_trip1_segment1_mode"] : '99'),
        (!empty($_POST["day7_trip1_segment2_mode"]) ? $_POST["day7_trip1_segment1_mode"] : '99'),
        (!empty($_POST["day7_trip1_segment3_mode"]) ? $_POST["day7_trip1_segment1_mode"] : '99'),
        (!empty($_POST["day7_trip1_segment1_distance"]) ? $_POST["day7_trip1_segment1_distance"] : '99'),
        (!empty($_POST["day7_trip1_segment2_distance"]) ? $_POST["day7_trip1_segment2_distance"] : '99'),
        (!empty($_POST["day7_trip1_segment3_distance"]) ? $_POST["day7_trip1_segment3_distance"] : '99'),
        (!empty($_POST["day7_trip1_segment1_duration"]) ? $_POST["day7_trip1_segment1_duration"] : '99'),
        (!empty($_POST["day7_trip1_segment2_duration"]) ? $_POST["day7_trip1_segment2_duration"] : '99'),
        (!empty($_POST["day7_trip1_segment3_duration"]) ? $_POST["day7_trip1_segment3_duration"] : '99'),
        (!empty($_POST["day7_trip1_segment1_cost"]) ? $_POST["day7_trip1_segment1_cost"] : '99'),
        (!empty($_POST["day7_trip1_segment2_cost"]) ? $_POST["day7_trip1_segment2_cost"] : '99'),
        (!empty($_POST["day7_trip1_segment3_cost"]) ? $_POST["day7_trip1_segment3_cost"] : '99'),
        (!empty($_POST["day7_trip1_segment1_time"]) ? $_POST["day7_trip1_segment1_time"] : '99'),
        (!empty($_POST["day7_trip1_segment2_time"]) ? $_POST["day7_trip1_segment2_time"] : '99'),
        (!empty($_POST["day7_trip1_segment3_time"]) ? $_POST["day7_trip1_segment3_time"] : '99'),

        //day 7 trip 2
        (!empty($_POST["day7_trip2_origin"]) ? $_POST["day7_trip2_origin"] : '99'),
        (!empty($_POST["day7_trip2_destination"]) ? $_POST["day7_trip2_destination"] : '99'),
        (!empty($_POST["day7_trip2_purpose"]) ? $_POST["day7_trip2_purpose"] : '99'),
        (!empty($_POST["day7_trip2_segment1_mode"]) ? $_POST["day7_trip2_segment1_mode"] : '99'),
        (!empty($_POST["day7_trip2_segment2_mode"]) ? $_POST["day7_trip2_segment1_mode"] : '99'),
        (!empty($_POST["day7_trip2_segment3_mode"]) ? $_POST["day7_trip2_segment1_mode"] : '99'),
        (!empty($_POST["day7_trip2_segment1_distance"]) ? $_POST["day7_trip2_segment1_distance"] : '99'),
        (!empty($_POST["day7_trip2_segment2_distance"]) ? $_POST["day7_trip2_segment2_distance"] : '99'),
        (!empty($_POST["day7_trip2_segment3_distance"]) ? $_POST["day7_trip2_segment3_distance"] : '99'),
        (!empty($_POST["day7_trip2_segment1_duration"]) ? $_POST["day7_trip2_segment1_duration"] : '99'),
        (!empty($_POST["day7_trip2_segment2_duration"]) ? $_POST["day7_trip2_segment2_duration"] : '99'),
        (!empty($_POST["day7_trip2_segment3_duration"]) ? $_POST["day7_trip2_segment3_duration"] : '99'),
        (!empty($_POST["day7_trip2_segment1_cost"]) ? $_POST["day7_trip2_segment1_cost"] : '99'),
        (!empty($_POST["day7_trip2_segment2_cost"]) ? $_POST["day7_trip2_segment2_cost"] : '99'),
        (!empty($_POST["day7_trip2_segment3_cost"]) ? $_POST["day7_trip2_segment3_cost"] : '99'),
        (!empty($_POST["day7_trip2_segment1_time"]) ? $_POST["day7_trip2_segment1_time"] : '99'),
        (!empty($_POST["day7_trip2_segment2_time"]) ? $_POST["day7_trip2_segment2_time"] : '99'),
        (!empty($_POST["day7_trip2_segment3_time"]) ? $_POST["day7_trip2_segment3_time"] : '99'),

        //day 7 trip 3
        (!empty($_POST["day7_trip3_origin"]) ? $_POST["day7_trip3_origin"] : '99'),
        (!empty($_POST["day7_trip3_destination"]) ? $_POST["day7_trip3_destination"] : '99'),
        (!empty($_POST["day7_trip3_purpose"]) ? $_POST["day7_trip3_purpose"] : '99'),
        (!empty($_POST["day7_trip3_segment1_mode"]) ? $_POST["day7_trip3_segment1_mode"] : '99'),
        (!empty($_POST["day7_trip3_segment2_mode"]) ? $_POST["day7_trip3_segment1_mode"] : '99'),
        (!empty($_POST["day7_trip3_segment3_mode"]) ? $_POST["day7_trip3_segment1_mode"] : '99'),
        (!empty($_POST["day7_trip3_segment1_distance"]) ? $_POST["day7_trip3_segment1_distance"] : '99'),
        (!empty($_POST["day7_trip3_segment2_distance"]) ? $_POST["day7_trip3_segment2_distance"] : '99'),
        (!empty($_POST["day7_trip3_segment3_distance"]) ? $_POST["day7_trip3_segment3_distance"] : '99'),
        (!empty($_POST["day7_trip3_segment1_duration"]) ? $_POST["day7_trip3_segment1_duration"] : '99'),
        (!empty($_POST["day7_trip3_segment2_duration"]) ? $_POST["day7_trip3_segment2_duration"] : '99'),
        (!empty($_POST["day7_trip3_segment3_duration"]) ? $_POST["day7_trip3_segment3_duration"] : '99'),
        (!empty($_POST["day7_trip3_segment1_cost"]) ? $_POST["day7_trip3_segment1_cost"] : '99'),
        (!empty($_POST["day7_trip3_segment2_cost"]) ? $_POST["day7_trip3_segment2_cost"] : '99'),
        (!empty($_POST["day7_trip3_segment3_cost"]) ? $_POST["day7_trip3_segment3_cost"] : '99'),
        (!empty($_POST["day7_trip3_segment1_time"]) ? $_POST["day7_trip3_segment1_time"] : '99'),
        (!empty($_POST["day7_trip3_segment2_time"]) ? $_POST["day7_trip3_segment2_time"] : '99'),
        (!empty($_POST["day7_trip3_segment3_time"]) ? $_POST["day7_trip3_segment3_time"] : '99'),

        //day 7 trip 4
        (!empty($_POST["day7_trip4_origin"]) ? $_POST["day7_trip4_origin"] : '99'),
        (!empty($_POST["day7_trip4_destination"]) ? $_POST["day7_trip4_destination"] : '99'),
        (!empty($_POST["day7_trip4_purpose"]) ? $_POST["day7_trip4_purpose"] : '99'),
        (!empty($_POST["day7_trip4_segment1_mode"]) ? $_POST["day7_trip4_segment1_mode"] : '99'),
        (!empty($_POST["day7_trip4_segment2_mode"]) ? $_POST["day7_trip4_segment1_mode"] : '99'),
        (!empty($_POST["day7_trip4_segment3_mode"]) ? $_POST["day7_trip4_segment1_mode"] : '99'),
        (!empty($_POST["day7_trip4_segment1_distance"]) ? $_POST["day7_trip4_segment1_distance"] : '99'),
        (!empty($_POST["day7_trip4_segment2_distance"]) ? $_POST["day7_trip4_segment2_distance"] : '99'),
        (!empty($_POST["day7_trip4_segment3_distance"]) ? $_POST["day7_trip4_segment3_distance"] : '99'),
        (!empty($_POST["day7_trip4_segment1_duration"]) ? $_POST["day7_trip4_segment1_duration"] : '99'),
        (!empty($_POST["day7_trip4_segment2_duration"]) ? $_POST["day7_trip4_segment2_duration"] : '99'),
        (!empty($_POST["day7_trip4_segment3_duration"]) ? $_POST["day7_trip4_segment3_duration"] : '99'),
        (!empty($_POST["day7_trip4_segment1_cost"]) ? $_POST["day7_trip4_segment1_cost"] : '99'),
        (!empty($_POST["day7_trip4_segment2_cost"]) ? $_POST["day7_trip4_segment2_cost"] : '99'),
        (!empty($_POST["day7_trip4_segment3_cost"]) ? $_POST["day7_trip4_segment3_cost"] : '99'),
        (!empty($_POST["day7_trip4_segment1_time"]) ? $_POST["day7_trip4_segment1_time"] : '99'),
        (!empty($_POST["day7_trip4_segment2_time"]) ? $_POST["day7_trip4_segment2_time"] : '99'),
        (!empty($_POST["day7_trip4_segment3_time"]) ? $_POST["day7_trip4_segment3_time"] : '99'),
        
    ]
];
$myfile = fopen("App.csv", "a") or die("Unable to open file!");
foreach ($list as $fields) {
    fputcsv($myfile, $fields);
}

fclose($myfile);
?>
<a href="index.php">Home Page</a>
<a href="app.csv" type="download">Download</a>